### ISSUE TITLE
overpass turbo hangs while rendering

### ISSUE THREAD

**Issue by GerdP** [tyrasd/overpass-turbo#450]
See 
https://github.com/drolbr/Overpass-API/issues/558#issuecomment-579722513
(Sorry, for me overpass api and overpass-turbo are synonyms. Will try to be more careful where I report issues)

**Comment by mmd-osm** [comment]
> for me overpass api and overpass-turbo are synonyms

It's pretty much like OSM API vs. JOSM. The backend manages the data, the frontend has the UI.

**Comment by GerdP** [comment]
Yes, that's understood now.

**Comment by BrianMacIntosh** [comment]
I have a call stack for this issue:
`Uncaught TypeError: Cannot read properties of undefined (reading 'lat')
    at Object.project (leaflet-src.js:1764:45)
    at Object.latLngToPoint (leaflet-src.js:1601:42)
    at GeoJsonNoVanish.<anonymous> (GeoJsonNoVanish.ts:53:22)
    at GeoJsonNoVanish.eachLayer (leaflet-src.js:7177:13)
    at GeoJsonNoVanish._onZoomEnd (GeoJsonNoVanish.ts:26:10)
    at GeoJsonNoVanish.onAdd (GeoJsonNoVanish.ts:12:10)
    at GeoJsonNoVanish._layerAdd (leaflet-src.js:6897:10)
    at I.whenReady (leaflet-src.js:4590:15)
    at I.addLayer (leaflet-src.js:6955:10)
    at GeoJsonNoVanish.addTo (leaflet-src.js:6835:9)`
I was using this query:
`{{geocodeArea:Irvine, CA}}->.searchArea;
nwr[fixme](area.searchArea)({{bbox}});
out;`
The UI gets stuck on "rendering geoJSON..."
On Edge Version 138.0.3351.77 (64-bit)
